package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"strings"
)

const orientationBanner = "<!-- generated by kazi (T4.4, ADR-0010) — do not edit; regenerated each dispatch -->\n"

// Only these controller-owned paths are admitted dynamically. Every other
// exception needs an explicit frozen digest, never a directory/glob exclusion.
func controllerArtifacts(cfg Config, k KaziEvaluation, baseline map[string]FileIdentity) (map[string]ControllerArtifact, error) {
	result := map[string]ControllerArtifact{}
	paths := map[string]bool{".kazi/context.md": true, ".mcp.json": true}
	for p := range k.Artifacts {
		paths[p] = true
	}
	for p := range paths {
		path := filepath.Join(cfg.Workspace, p)
		// Check every component; a symlinked parent cannot redirect an artifact audit.
		current := cfg.Workspace
		for _, part := range strings.Split(p, "/") {
			current = filepath.Join(current, part)
			info, err := os.Lstat(current)
			if errors.Is(err, os.ErrNotExist) {
				break
			}
			if err != nil {
				return nil, err
			}
			if info.Mode()&os.ModeSymlink != 0 {
				return nil, fmt.Errorf("controller artifact symlink: %s", p)
			}
		}
		info, err := os.Lstat(path)
		if errors.Is(err, os.ErrNotExist) {
			if k.Artifacts[p] != "" {
				return nil, fmt.Errorf("frozen controller artifact missing: %s", p)
			}
			continue
		}
		if err != nil {
			return nil, err
		}
		if !info.Mode().IsRegular() || info.Size() > 2<<20 {
			return nil, fmt.Errorf("invalid controller artifact: %s", p)
		}
		raw, err := os.ReadFile(path)
		if err != nil {
			return nil, err
		}
		hash := digest(raw)
		if want := k.Artifacts[p]; want != "" {
			if hash != want {
				return nil, fmt.Errorf("frozen controller artifact changed: %s", p)
			}
		} else {
			switch p {
			case ".kazi/context.md":
				if !strings.HasPrefix(string(raw), orientationBanner) {
					return nil, errors.New("unrecognized controller orientation file")
				}
			case ".mcp.json":
				var got any
				if err := json.Unmarshal(raw, &got); err != nil {
					return nil, err
				}
				want := map[string]any{"mcpServers": map[string]any{"code-review-graph": map[string]any{"command": "code-review-graph", "args": []any{"mcp"}}}}
				if !reflect.DeepEqual(got, want) {
					return nil, errors.New("MCP config needs an explicit frozen digest; default permits only canonical graph entry")
				}
			}
		}
		identity, err := fileIdentity(path)
		if err != nil {
			return nil, err
		}
		artifact := ControllerArtifact{FileIdentity: identity}
		if before, ok := baseline[p]; ok {
			artifact.Baseline = &before
		}
		result[p] = artifact
	}
	return result, nil
}
